export default function TermsPage() {
  const sections = [
    {
      title: "1. Acceptance",
      body: "By using My Tiny Tales (mytinytales.studio), you agree to these Terms of Service. If you do not agree, please do not use the service.",
    },
    {
      title: "2. The Service",
      body: "My Tiny Tales lets you create personalised AI-illustrated children's storybooks. We provide a free preview and paid digital download and print options. The service is intended for use by adults (18+) on behalf of children.",
    },
    {
      title: "3. Acceptable Use",
      body: "You may only upload photos for which you have the right to do so (e.g. your own child, with parental consent). You must not upload images of adults, explicit content, or anything that violates applicable law. We reserve the right to terminate access for misuse.",
    },
    {
      title: "4. Payments and Refunds",
      body: "Payments are processed by Stripe. Digital downloads are delivered immediately after payment. If your download is defective or substantially different from the preview you approved, contact us within 7 days for a resolution. We do not offer refunds for change-of-mind purchases on digital goods.",
    },
    {
      title: "5. Intellectual Property",
      body: "The storybook you create is for your personal, non-commercial use. You may print it, share it with family, and store it for personal enjoyment. You may not resell, redistribute, or use the generated images for commercial purposes.",
    },
    {
      title: "6. AI-Generated Content",
      body: "Storybook illustrations are generated by AI and may not be perfectly accurate. Character likenesses are approximate. We do not guarantee exact resemblance to any individual.",
    },
    {
      title: "7. Limitation of Liability",
      body: "My Tiny Tales is provided 'as is'. We are not liable for any indirect or consequential damages arising from use of the service. Our total liability to you shall not exceed the amount you paid for the relevant order.",
    },
    {
      title: "8. Changes",
      body: "We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the updated terms. Last updated: April 2025.",
    },
  ];

  return (
    <main style={{ minHeight: "100vh", background: "#0D0820", color: "#EDE8D5", fontFamily: "Georgia, serif" }}>
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "80px 24px" }}>
        <h1 style={{ fontSize: 40, fontWeight: 700, marginBottom: 8, color: "#F5A623" }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: 17, color: "#B8A9C9", marginBottom: 56 }}>
          Please read these terms before using My Tiny Tales.
        </p>

        <div style={{ display: "flex", flexDirection: "column", gap: 40 }}>
          {sections.map((s, i) => (
            <div key={i}>
              <h2 style={{ fontSize: 20, fontWeight: 600, marginBottom: 12, color: "#EDE8D5" }}>
                {s.title}
              </h2>
              <p style={{ fontSize: 16, lineHeight: 1.75, color: "#B8A9C9", margin: 0 }}>
                {s.body}
              </p>
            </div>
          ))}
        </div>

        <p style={{ marginTop: 56, fontSize: 14, color: "#6B5A7A" }}>
          Questions? Email{" "}
          <a href="mailto:hello@mytinytales.studio" style={{ color: "#B8A9C9" }}>
            hello@mytinytales.studio
          </a>
        </p>
      </div>
    </main>
  );
}
