import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service — My Tiny Tales" };

const PURPLE_DARK = "#1a0a2e";
const GOLD = "#f4c430";

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", background: "#fffef7", fontFamily: "var(--font-inter, 'Segoe UI', sans-serif)" }}>
      <nav style={{ background: PURPLE_DARK, padding: "16px 32px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <Link href="/" style={{ display: "flex", alignItems: "center", gap: 10, textDecoration: "none" }}>
          <span style={{ fontSize: 22 }}>✨</span>
          <span style={{ fontFamily: "var(--font-playfair, Georgia, serif)", fontWeight: 700, fontSize: 18, color: "white" }}>My Tiny Tales</span>
        </Link>
        <Link href="/create" style={{ textDecoration: "none", padding: "8px 20px", borderRadius: 50, background: `linear-gradient(135deg, ${GOLD}, #ffb347)`, color: PURPLE_DARK, fontWeight: 700, fontSize: 13 }}>
          Create a Book →
        </Link>
      </nav>

      <div style={{ maxWidth: 760, margin: "0 auto", padding: "60px 32px 80px" }}>
        <h1 style={{ fontFamily: "var(--font-playfair, Georgia, serif)", fontSize: 38, fontWeight: 700, color: PURPLE_DARK, marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ color: "#8a6d5a", fontSize: 14, marginBottom: 40 }}>Last updated: April 2026</p>

        {[
          {
            title: "1. Acceptance of Terms",
            body: `By using My Tiny Tales ("we", "our", "the Service"), you agree to these Terms of Service. If you do not agree, please do not use the Service. We may update these terms from time to time; continued use constitutes acceptance of any changes.`,
          },
          {
            title: "2. Use of the Service",
            body: `My Tiny Tales allows you to create personalised AI-generated children's storybooks. You must be at least 18 years old to purchase or use the Service. You may use the Service only for lawful personal purposes.

You agree not to: upload photos of individuals without their consent (or appropriate parental/guardian consent for minors); use the Service to generate offensive, harmful, or illegal content; attempt to reverse-engineer, copy, or resell any part of the Service.`,
          },
          {
            title: "3. Content Ownership",
            body: `The stories and illustrations generated by the Service are created for your personal use. Upon purchase, you receive a non-exclusive, non-transferable licence to download, print, and share your book for personal and non-commercial purposes.

You retain ownership of any photos you upload. By uploading a photo you grant us a limited, temporary licence to use it solely to generate your book. Photos are deleted immediately after generation.`,
          },
          {
            title: "4. Payments & Refunds",
            body: `Payments are processed securely by Stripe. Prices are displayed in USD and are inclusive of any applicable fees. We offer a 30-day happiness promise — we are committed to making sure you love your book. We handle all concerns on a case-by-case basis and are committed to your satisfaction. Please contact us at hello@mytinytales.studio within 30 days of purchase.

Digital books are delivered immediately upon payment. Print books are produced and shipped within 5–7 business days; shipping times vary by location. We are not responsible for delays caused by shipping carriers.`,
          },
          {
            title: "5. Intellectual Property",
            body: `The My Tiny Tales name, logo, website design, and proprietary technology are our intellectual property and may not be reproduced without permission. The AI-generated stories and illustrations are unique to each order; we do not claim copyright over the content generated for you.`,
          },
          {
            title: "6. Disclaimers",
            body: `The Service is provided "as is". AI-generated content may occasionally contain errors or unexpected results. We do not guarantee that generated images will meet every expectation, but we handle all concerns on a case-by-case basis and are committed to your satisfaction.`,
          },
          {
            title: "7. Limitation of Liability",
            body: `To the maximum extent permitted by law, My Tiny Tales shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount you paid for the order in question.`,
          },
          {
            title: "8. Governing Law",
            body: `These Terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.`,
          },
          {
            title: "9. Contact",
            body: `For any questions regarding these Terms, contact us at hello@mytinytales.studio.`,
          },
        ].map((s) => (
          <section key={s.title} style={{ marginBottom: 36 }}>
            <h2 style={{ fontFamily: "var(--font-playfair, Georgia, serif)", fontSize: 20, fontWeight: 700, color: PURPLE_DARK, marginBottom: 12 }}>{s.title}</h2>
            {s.body.split("\n\n").map((para, i) => (
              <p key={i} style={{ color: "#3d2b1f", fontSize: 15, lineHeight: 1.8, margin: "0 0 12px" }}>{para}</p>
            ))}
          </section>
        ))}
      </div>

      <footer style={{ background: PURPLE_DARK, padding: "24px 32px", textAlign: "center" }}>
        <p style={{ color: "rgba(255,255,255,0.35)", fontSize: 12, margin: 0 }}>
          © {new Date().getFullYear()} My Tiny Tales ·{" "}
          <Link href="/privacy" style={{ color: "rgba(255,255,255,0.35)", textDecoration: "none" }}>Privacy</Link>
          {" · "}
          <Link href="/contact" style={{ color: "rgba(255,255,255,0.35)", textDecoration: "none" }}>Contact</Link>
        </p>
      </footer>
    </div>
  );
}
